 steps:
 - id: install_packages
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'install'
 - id: prerender_browser_files
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'run'
   - 'build:prerender'