 steps:
 - id: install_packages
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'install'
 - id: prerender_browser_files
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'run'
   - 'build:prerender'

  # Build productive files
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build', '--prod' ]


- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/sri-illapani-sre-w1-project/angular-app', '.']
images: ['gcr.io/sri-illapani-sre-w1-project/angular-app']


  # Deploy to google cloud app egnine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=prod']