 steps:
 - id: install_packages
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'install'
 - id: prerender_browser_files
   name: 'gcr.io/cloud-builders/npm'
   args:
   - 'run'
   - 'build:prerender'
   waitFor:
   - install_packages
 - id: copy_prerendered_files
   name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp','-r','dist/browser/*', '\${_ANGULAR_APP_BUCKET_PATH}']
   waitFor:
   - prerender_browser_files
 - id: set_website_configuration
   name: 'gcr.io/cloud-builders/gsutil'
   args: ['web', 'set', '-m', 'index.html','\${_ANGULAR_APP_BUCKET_PATH}']
   waitFor:
   - copy_prerendered_files
 - id: set_permissions_for_website_files
   name: 'gcr.io/cloud-builders/gsutil'
   args: ['acl','ch','-u','AllUsers:R','-r', '\${_ANGULAR_APP_BUCKET_PATH}']
   waitFor:
   - copy_prerendered_files